FROM arm32v7/node:11 as build-env

WORKDIR /usr/src/app
COPY . .

RUN npm install -g lerna && npm run bootstrap && npm run build

FROM arm32v7/node:11

WORKDIR /usr/src/app

COPY --from=build-env ./src/aux-server/package*.json ./

RUN npm install --only=production

COPY --from=build-env ./src/aux-server/server/dist ./server/dist/
COPY --from=build-env ./src/aux-server/aux-web/dist ./aux-web/dist/

ENV PRODUCTION 1

# HTTP
EXPOSE 3000

# WebSocket
EXPOSE 4567

CMD [ "npm", "start" ]
