FROM node:16

WORKDIR /usr/src/app

COPY ./script/remove-dev-dependencies.js ./script/remove-dev-dependencies.js
COPY ./src/aux-auth/package*.json ./

RUN node ./script/remove-dev-dependencies.js ./package.json
RUN npm install

COPY ./src/aux-auth/server/dist ./server/dist/
COPY ./src/aux-auth/web/dist ./web/dist/

ENV PRODUCTION 1

# HTTP
EXPOSE 2998

CMD [ "npm", "start" ]
