version: 0.2

env:
    secrets-manager:
        DOCKERHUB_USER: codebuild/publish-casualos-docker:DOCKERHUB_USER
        DOCKERHUB_TOKEN: codebuild/publish-casualos-docker:DOCKERHUB_TOKEN
        GITHUB_USER: codebuild/publish-casualos-docker:GITHUB_USER
        GITHUB_TOKEN: codebuild/publish-casualos-docker:GITHUB_TOKEN

phases:
    install:
        runtime-versions:
            nodejs: 16
        commands:
            - echo Executing Install Phase
            - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
            - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
        finally:
            - echo Executing Install Finally
    pre_build:
        commands:
            - echo Executing Pre Build Phase
            - npm ci
            - npm run bootstrap
            - cd docs && yarn && cd ..
        finally:
            - echo Executing Pre Build Finally
    build:
        commands:
            - echo Executing Build Phase
            - |
                set -e
                npm run build

                GIT_TAG=$(git describe --abbrev=0 --tags)

                echo "Login to DockerHub..."
                echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USER" --password-stdin

                echo "Git Tag: $GIT_TAG"

                docker build -t casualos -f Dockerfile.arm64 .
                docker tag casualos casualsimulation/aux-arm64:$GIT_TAG
                docker tag casualos casualsimulation/aux-arm64:latest
                docker tag casualos casualsimulation/aux-arm64:alpha
                docker tag casualos ghcr.io/casual-simulation/casualos-arm64:$GIT_TAG
                docker tag casualos ghcr.io/casual-simulation/casualos-arm64:latest
                docker tag casualos ghcr.io/casual-simulation/casualos-arm64:alpha
            - |
                set -e

                GIT_BRANCH=$(git symbolic-ref HEAD --short -q || echo "")

                if [ "$GIT_BRANCH" == "" ] ; then
                  echo "3."
                  GIT_BRANCH=$(git branch -a --contains HEAD | grep master | awk '{ printf $1 }')
                  GIT_BRANCH=${GIT_BRANCH#remotes/origin/}
                fi

                GIT_TAG=$(git describe --abbrev=0 --tags)

                echo "Upload to DockerHub..."
                docker push casualsimulation/aux-arm64:$GIT_TAG
                if [ "$GIT_BRANCH" == "master" ] ; then
                  docker push casualsimulation/aux-arm64:latest
                else
                  docker push casualsimulation/aux-arm64:alpha
                fi

                echo "Login to GHCR..."
                echo "$GITHUB_TOKEN" | docker login ghcr.io -u "$GITHUB_USER" --password-stdin

                echo "Upload to GHCR..."
                docker push ghcr.io/casual-simulation/casualos-arm64:$GIT_TAG
                if [ "$GIT_BRANCH" == "master" ] ; then
                  docker push ghcr.io/casual-simulation/casualos-arm64:latest
                else
                  docker push ghcr.io/casual-simulation/casualos-arm64:alpha
                fi
        finally:
            - echo Executing Build Finally
    post_build:
        commands:
            - echo Executing Post Build Phase
        finally:
            - echo Executing Post Build Finally
