version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 14
        commands:
            - echo Executing Install Phase
            - yarn
        finally:
            - echo Executing Install Finally
    pre_build:
        commands:
            - echo Executing Pre Build Phase
            - npm run bootstrap
        finally:
            - echo Executing Pre Build Finally
    build:
        commands:
            - echo Executing Build Phase

            - echo Building packages...
            - npm run build:libs

            - echo Building web...
            - npx lerna exec --scope @casual-simulation/aux-server -- npm run build:web

            - echo Packaging Config...
            - npm run package:config
        finally:
            - echo Executing Build Finally
    post_build:
        commands:
            - echo Executing Post Build Phase
            - echo Copying to S3...
            - aws s3 sync src/aux-server/aux-web/dist $S3_BUCKET --delete

            # Copy the HTML files with a specific cache-control header
            - aws s3 cp src/aux-server/aux-web/dist/index.html $S3_BUCKET/index.html --cache-control no-cache
            - aws s3 cp src/aux-server/aux-web/dist/player.html $S3_BUCKET/player.html --cache-control no-cache
            - aws s3 cp src/aux-server/aux-web/dist/aux-vm-iframe.html $S3_BUCKET/aux-vm-iframe.html --cache-control no-cache

            - aws s3 cp src/aux-server/aux-web/dist/api/config $S3_BUCKET/api/config --cache-control no-cache
            - aws s3 cp src/aux-server/aux-web/dist/terms $S3_BUCKET/terms --content-type text/plain
            - aws s3 cp src/aux-server/aux-web/dist/privacy-policy $S3_BUCKET/privacy-policy --content-type text/plain
            - aws s3 cp src/aux-server/aux-web/dist/acceptable-use-policy $S3_BUCKET/acceptable-use-policy --content-type text/plain

            - echo Invalidating CloudFront...
            - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION --paths "/*"
            - echo Done!

        finally:
            - echo Executing Post Build Finally
