packer {
  required_version = ">= 0.12.0"
  required_plugins {
    amazon = {
      source  = "github.com/hashicorp/amazon"
      version = "~> 1"
    }
  }
}

variable "aws_region" {
  type    = string
  default = "us-east-1"
}

variable "node_version" {
  type    = string
  default = "20.18.3"
}

data "amazon-ami" "autogenerated_1" {
  filters = {
    architecture                       = "arm64"
    "block-device-mapping.volume-type" = "gp2"
    name                               = "ubuntu/images/hvm-ssd/ubuntu-focal-20.04-arm64-server-*"
    root-device-type                   = "ebs"
    virtualization-type                = "hvm"
  }
  most_recent = true
  owners      = ["099720109477"]
  profile     = "casualsimulation"
  region      = "${var.aws_region}"
}

locals { timestamp = regex_replace(timestamp(), "[- TZ:]", "") }

source "amazon-ebs" "ubuntu20-ami" {
  ami_description = "A Ubuntu 20.04 AMI that has Node.js and Docker"
  ami_name        = "nodejs-docker-ubuntu20-${local.timestamp}"
  instance_type   = "t4g.micro"
  profile         = "casualsimulation"
  region          = "${var.aws_region}"
  source_ami      = "${data.amazon-ami.autogenerated_1.id}"
  ssh_username    = "ubuntu"
}

build {
  sources = ["source.amazon-ebs.ubuntu20-ami"]

  provisioner "shell" {
    script = "${path.root}/install-aws-cli.sh"
  }

  provisioner "shell" {
    script = "${path.root}/install-docker.sh"
  }

  provisioner "shell" {
    environment_vars = ["NODE_VERSION=${var.node_version}"]
    script           = "${path.root}/install-nodejs.sh"
  }

}
