/**
 * Defines an interface that is able to send and receive AI chat messages.
 */
export interface AIChatInterface {
    /**
     * Sends a chat request to the AI API.
     * @param request The request to send.
     */
    chat(request: AIChatRequest): Promise<AIChatResponse>;
}

/**
 * Defines an interface that represents an AI chat request.
 */
export interface AIChatRequest {
    /**
     * The model that should be used.
     */
    model: string;

    /**
     * The messages that should be sent to the AI.
     */
    messages: AIChatMessage[];

    /**
     * The temperature of the request.
     */
    temperature: number;
}

/**
 * Defines an interface that represents an AI chat response.
 */
export interface AIChatResponse {
    /**
     * The messages that the AI responded with.
     */
    choices: AIChatChoice[];
}

/**
 * Defines an interface that represents a single chat choice in a conversation with an AI.
 */
export interface AIChatChoice {
    /**
     * The reason why the message was finished.
     */
    finishReason: string;

    /**
     * The message generated by the AI.
     */
    message: AIChatMessage;
}

/**
 * Defines an interface that represents a single chat message in a conversation with an AI.
 *
 * @dochash types/ai
 * @docname AIChatMessage
 */
export interface AIChatMessage {
    /**
     * The role of the message.
     *
     * - `system` means that the message was generated by the system. Useful for telling the AI how to behave while.
     * - `user` means that the message was generated by the user.
     * - `assistant` means that the message was generated by the AI assistant.
     * - `function` means that the message contains the results of a function call.
     */
    role: 'system' | 'user' | 'assistant' | 'function';

    /**
     * The contents of the message.
     */
    content: string;

    /**
     * The name of the author of the message.
     *
     * This is required if the role is `function`.
     */
    author?: string;

    /**
     * @hidden
     */
    functionCall?: AIFunctionCall;
}

/**
 * Defines an interface that represents an AI function call.
 */
export interface AIFunctionCall {
    name: string;

    /**
     * The arguments that should be passed to the function.
     */
    arguments: {
        [key: string]: any;
    };
}
