receivers:
    otlp:
        protocols:
            grpc:
                endpoint: 0.0.0.0:4317
            http:
                endpoint: 0.0.0.0:4318
exporters:
    otlp:
        endpoint: tempo:4317
        tls:
            insecure: true
    prometheus:
        endpoint: 0.0.0.0:4319
        namespace: casualos

service:
    pipelines:
        traces:
            receivers: [otlp]
            exporters: [otlp]
        metrics:
            receivers: [otlp]
            exporters: [prometheus]
