global:
    scrape_interval: 15s
    evaluation_interval: 15s

scrape_configs:
    - job_name: 'otel'
      static_configs:
          - targets: ['otel-collector:4319']
    - job_name: 'tempo'
      static_configs:
          - targets: ['tempo:3200']
