name: Claude Code (Issues & PRs)

on:
    issue_comment:
        types: [created]
    workflow_dispatch: {}

permissions:
    contents: write
    pull-requests: write
    issues: read

jobs:
    claude:
        runs-on: ubuntu-latest

        # 👇 This is the key: attach your environment so its secrets are available.
        environment: ai-api-keys

        # Only trigger on manual run OR when someone says '@claude'
        if: |
            github.event_name == 'workflow_dispatch' ||
            (github.event_name == 'issue_comment' &&
             contains(github.event.comment.body, '@claude'))

        steps:
            - uses: actions/checkout@v4

            # ===== OPTION A: Direct Anthropic API key stored in the environment =====
            # Expected environment secret names (create in Settings → Environments → ai-api-keys):
            #   - ANTHROPIC_API_KEY
            # Optionally:
            #   - CLAUDE_MODEL  (e.g., 'claude-3-7-sonnet-20250219')
            #   - EXTRA_TASKS   (your custom shell steps; see plan below)
            - name: Run Claude Code via Anthropic API
              if: ${{ secrets.ANTHROPIC_API_KEY != '' }}
              uses: anthropics/claude-code-action@v1
              with:
                  trigger: '@claude'
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  model: ${{ secrets.CLAUDE_MODEL_1 }}
                  plan: |
                      You are a senior engineer. Read the linked issue/comment context.
                      - Create a branch: fix/${{ github.event.issue.number || 'manual' }}-<short-slug>
                      - Implement the fix with small, reviewable commits.
                      - Try to run tests/linters if found:
                        * npm ci && npm test && npm run lint
                        * or: make test
                      - If $EXTRA_TASKS is set, run it.
                      - Open a PR that:
                        * references the issue (Fixes #<num>)
                        * explains root cause, changes, risks, and test notes
                        * requests review from @${{ github.actor }}
              env:
                  ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
                  EXTRA_TASKS: ${{ secrets.EXTRA_TASKS }}
